### ISSUE TITLE
Iterations required for the faster rcnn model

### ISSUE THREAD

**Issue by amlandas78** [Information-Fusion-Lab-Umass/Salient-Pedestrian-Detection#2]
Can you please tell me the number of iterations required for the faster rcnn model that you have trained using the pretrained Imagenet models?

**Comment by DebasmitaGhose** [comment]
We trained Faster RCNN for 6 epochs, batch size = 1 and on approximately 7600 training images.

**Comment by amlandas78** [comment]
Is it the IMS_PER_BATCH or the BATCH_SIZE configuration?

**Comment by DebasmitaGhose** [comment]
both have been set to 1
