### ISSUE TITLE
About the database

### ISSUE THREAD

**Issue by Brain-Lee** [Information-Fusion-Lab-Umass/Salient-Pedestrian-Detection#3]
Can you please share your KAIST database for training Faster R-CNN？I use the same methods in your paper to process datasets, but I can't get the same number of images.

**Comment by Brain-Lee** [comment]
And I have one more question。The paper says that  replacing one duplicate channel of the 3-channel thermal images with the corresponding saliency maps。You mean to add two duplicate thermal images and one saliency maps, or use other methods?

**Comment by DebasmitaGhose** [comment]
The KAIST Salient Pedestrian dataset is available on the project website for download. Please let us know if you are having issues downloading it. 
We have created an image with two channels duplicated from the one channel thermal image and the the third channel to be the saliency map

**Comment by Brain-Lee** [comment]
Thank you very much for your reply。Does the third channel refer to the red channel of BGR channel？

**Comment by Brain-Lee** [comment]
And there's no problem downloading the database.I have downloaded the database

**Comment by DebasmitaGhose** [comment]
It does not make a difference. You can replace either of the three channels since the original thermal images are grayscale. They were read as a 3 channel image because Faster RCNN needs a 3 channel image.

**Comment by Brain-Lee** [comment]
Have you ever tried to overlay two original thermal images with one saliency map image.In other words, a image used for training consists of two-thirds of original thermal images and one-third of saliency map image.To increase the brightness of pedestrian areas.Is the effect going to be bad or haven't you tried.

**Comment by DebasmitaGhose** [comment]
We havent tried that. For us replacing one of the channels does the job of making the pedestrians brighter in the image.

**Comment by Brain-Lee** [comment]
OK, I got it. Thank you again for your reply.

**Comment by DebasmitaGhose** [comment]
No problem. Feel free to get back to us with further questions.
